version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: redlock-web-2.0
    ports:
      - "7077:80"
    volumes:
      - ./web:/var/www/vinsen


  isi_data:
    image: mysql:latest
    container_name: redlock-web-2.0-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vinsen123
    volumes:
      - ./redlock-dbs.sql:/docker-entrypoint-initdb.d/redlock-dbs.sql